In [165]:
#클래스 실습 01 
#name,cc,year

class Car:
    car_count = 0

    def __init__(self,name,cc,year): #차이름 변경 함수 
        self.__name = name
        self.__cc = cc
        self.__year = year
        
        Car.car_count += 1
                
    def name(self):
        print(f"{self.__name}")
        
    def cc(self):
        if int(self.__cc) < 1000:
            print("소형")
        elif 1000 <= int(self.__cc) <= 2000:
            print("중형")
        elif int(self.__cc) > 2000:
            print("대형")
    
    def changename(self):
        newname = input("바꿀 이름 : ")
        self.__name = newname
        print(self.__name)
            
    @classmethod        
    def carcount(self):
        print("총 자동차 수는:",Car.car_count,"대")

In [166]:
k3 = Car("k3","1000","2020")

In [167]:
k5 = Car("k5","1500","2020")

In [168]:
k7 = Car("k7","2100","2020")

In [169]:
k3.name()
k3.cc()
k3.carcount()

k3
중형
총 자동차 수는: 3 대


In [147]:
k7.carcount()

총 자동차 수는: 3 대


In [148]:
k7.name()
k7.cc()
k7.carcount()

k7
대형
총 자동차 수는: 3 대


In [16]:
#클래스 실습 01 
#name,cc,year

class Car:
    car_count = 0

    def __init__(self,name,cc,year): #차이름 변경 함수 
        self.__name = name
        self.__cc = cc
        self.__year = year
        
        Car.car_count += 1
                
    def name(self):
        print(f"차종은 {self.__name}입니다.")
        
    def cc(self):
        if int(self.__cc) < 1000:
            print("소형")
        elif 1000 <= int(self.__cc) <= 2000:
            print("중형")
        else:
            print("대형")
    
    def changename(self, newname):
        self.__name = newname
        
            
    @classmethod        
    def carcount(cls):
        print("총 자동차 수는:",Car.car_count,"대")

In [17]:
k3 = Car("k3",900,2020)

In [18]:
k3.changename(k5)

NameError: name 'k5' is not defined

In [171]:
Car.carcount()

총 자동차 수는: 0 대


In [198]:
import pickle

try:
    with open("data3.p","rb") as file:
        name=pickle.load(file)
        address=pickle.load(file)
        email=pickle.load(file)
        
        print(name,address,email)

except FileNotFoundError as e:
    print("file이 존재하지 않습니다.")
    name = input("이름 : ")
    address = input("주소 : ")
    email = input("이메일 : ")
    
    data = {"이름":name, "주소":address, "이메일":email}
    
    with open("data3.p","wb") as file:
        pickle.dump(name,file)
        pickle.dump(address,file)
        pickle.dump(email,file)
        
    print("file이 생성되었습니다.")

홍길동 서울시 aa@aa.com


In [180]:
import pickle

with open("data3.p","rb") as file:
        name=pickle.load(file)
        address=pickle.load(file)
        email=pickle.load(file)
        
        print(data)

{'이름': '홍길동', '주소': '서울시', '이메일': 'aa@aa.com'}


In [4]:
import pkcalc.calc as calc

print(calc.add(5,6))
print(calc.sub(5,6))

11
-1


In [6]:
from pkcalc.calc import add

print(add(5,6))

11


In [7]:
import sys
print(sys.path)

['C:\\Users\\mmqq2\\Kdigital\\lab', 'C:\\Users\\mmqq2\\anaconda3\\python38.zip', 'C:\\Users\\mmqq2\\anaconda3\\DLLs', 'C:\\Users\\mmqq2\\anaconda3\\lib', 'C:\\Users\\mmqq2\\anaconda3', '', 'C:\\Users\\mmqq2\\anaconda3\\lib\\site-packages', 'C:\\Users\\mmqq2\\anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\mmqq2\\anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\mmqq2\\anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\mmqq2\\anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\mmqq2\\.ipython']


In [8]:
import pkcalc

In [11]:
print(calc.add(5,6))

11


In [8]:
import numpy as np

In [13]:
import pandas as pd

In [14]:
matrix_1 = [[1, 2], [3, 4]]
matrix_2 = [[5, 6], [7, 8]]

In [16]:
#matrix 원소의 합
c = []

for i in range(len(matrix_1)):
    temp = []
    for j in range(len(matrix_1[i])):
        temp.append(matrix_1[i][j]+matrix_2[i][j])
    c.append(temp)

print(c)                        

[[6, 8], [10, 12]]


In [23]:
#matrix_1의 원소에 1 더하기
c = []

for i in range(len(matrix_1)):
    temp = []
    for j in range(len(matrix_1[i])):
        temp.append(matrix_1[i][j] + 1)
    c.append(temp)
    
print(c)

[[2, 3], [4, 5]]


In [30]:
#matrix_1의 원소에 1 더하기
c = []

for i in range(len(matrix_1)):
    temp = []
    for j in range(len(matrix_1[i])):
        temp.append(matrix_1[i][j] + 1)
    c.append(temp)
    
print(matrix_1[0][1])

2


In [45]:
matrix_1 = [[1, 2], [3, 4]]
matrix_2 = [[5, 6], [7, 8]]

In [32]:
def matrix_sum(mat_1, mat_2):
    for i in range(len(matrix_1)):
        for j in range(len(matrix_1[0])):
            mat_1[i][j] += mat_2[i][j]
            
    return mat_1

In [35]:
matrix_sum(matrix_1,matrix_2)
print(matrix_1)

[[6, 8], [10, 12]]


In [ ]:
matrix_1 = [[1, 2], [3, 4]]
matrix_2 = [[5, 6], [7, 8]]

In [46]:
def mat_add_one(mat):
    for i in range(len(mat)):
        for j in range(len(mat[0])):
            mat[i][j] += 1
    return mat

In [47]:
mat_add_one(matrix_1)
matrix_1

[[2, 3], [4, 5]]

In [48]:
matrix_1 = [[1, 2], [3, 4]]
matrix_2 = [[5, 6], [7, 8]]

In [49]:
mat_sum = np.array(matrix_1) + np.array(matrix_2)
print(mat_sum)

[[ 6  8]
 [10 12]]


In [50]:
mat_one = np.array(matrix_1) + 1
print(mat_one)

[[2 3]
 [4 5]]


In [51]:
import time

In [52]:
size = 10000000

In [53]:
x = list(range(size))
y = list(range(size))

In [54]:
start_time = time.time()
z = [x[i]+y[i] for i in range(size)]
print("리스트 걸린시간",time.time()-start_time)

리스트 걸린시간 2.4715735912323


In [55]:
x = np.arange(size)
y = np.arange(size)
start_time = time.time()
z = x + y
print("넘파이 걸린시간",time.time()-start_time)

넘파이 걸린시간 0.15477371215820312


In [9]:
x = np.uint(32)
print(x)
print(type(x))
print(x.dtype)

32
<class 'numpy.uint32'>
uint32


In [10]:
x = np.array([1,2,3,4])
print(x)
print(type(x))
print(x.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int32


In [11]:
x = np.float32([1,2,3,4])
print(x)
print(type(x))
print(x.dtype)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float32


In [12]:
x = np.array([1,2,3,4], dtype=np.float32)
print(x)
print(type(x))
print(x.dtype)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float32


In [13]:
x = np.int32(x)
print(x.dtype)
print(x)

int32
[1 2 3 4]


In [14]:
np.issubdtype(x.dtype,np.int32)

True

In [15]:
np.issubdtype(x.dtype,np.int32)

True