In [12]:
#클래스 실습 02

class Character:
    def __init__(self):
        self.health = 200
    
    def move(self):
        self.health -= 10
        
    def rest(self):
        self.health += 10
        
    def checkhealth(self):
        print("Health : ",self.health)

In [13]:
class Knight(Character):
    def move(self):
        self.health -= 15
    
    def attack(self):
        print("공격합니다.")    

In [14]:
class Healer(Character):
    def __init__(self):
        super().__init__()
        self.mana = 100
        
    def heal(self,character):
        self.mana -= 10
        character.rest()
        
    def checkmana(self):
        print("Mana : ",self.mana)

In [17]:
import numpy as np

In [21]:
x = np.array([[[1, 2, 3, 3], [2, 3, 4, 5], [1, 2, 3, 6]], [[1, 2, 3, 3], [2, 3, 4, 5], [1, 2, 3, 6]]])
print(x.shape)

(2, 3, 4)


In [23]:
x = np.linspace(1,50) #linspace
print(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]


In [26]:
a = np.arange(20).reshape(4,5)#reshape
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [28]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [29]:
print(x[1:3])

[1 2]


In [30]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [33]:
x = x.reshape(4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [34]:
x = np.arange(20).reshape(4,5)
print(x[1:3])

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [35]:
x = np.arange(20).reshape(4,5)
print(x[1:3, 1:3])

[[ 6  7]
 [11 12]]


In [37]:
x = np.arange(30).reshape(2,5,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [140]:
x = np.arange(30).reshape(2,5,3) #slicing
print(x[:])
print()
print(x[:, 3:5])
print()
print(x[:, 3:5, 1])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]

[[[ 9 10 11]
  [12 13 14]]

 [[24 25 26]
  [27 28 29]]]

[[10 13]
 [25 28]]


In [44]:
a = np.arange(20).reshape(4,5) #indexing
print(a)
print(a[1][1])
print(a[1,1])
print(a[[1,1],[1,2]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
6
6
[6 7]


In [54]:
a = np.arange(20).reshape(4,5) #boolean indexing
print(a>3)
print(a==3)
print(a!=3)
print(a[a>3])
print(a[a==1])
print(a[~(a==1)])# = print(a[a!=1])
print(a[(a>3)&(a<8)])

[[False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[False False False  True False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[[ True  True  True False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1]
[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[4 5 6 7]


In [58]:
np.random.rand(2,3,4)

array([[[0.47092682, 0.83588972, 0.07189651, 0.30346045],
        [0.21524139, 0.44826727, 0.91743759, 0.35708985],
        [0.89595911, 0.95702994, 0.95264674, 0.31576044]],

       [[0.73450783, 0.47646522, 0.26089778, 0.11328902],
        [0.63710211, 0.03948326, 0.0027063 , 0.18151367],
        [0.8285243 , 0.9530924 , 0.02430699, 0.44496982]]])

In [60]:
np.random.randint(1,10,size=(2,3,4))

array([[[9, 7, 2, 9],
        [7, 1, 7, 9],
        [6, 9, 6, 7]],

       [[3, 7, 2, 8],
        [2, 3, 4, 7],
        [4, 9, 8, 6]]])

In [64]:
x = np.random.randint(1,10,size=(2,3))
print(x)

[[5 4 2]
 [1 9 3]]


In [67]:
x.ravel()

array([5, 4, 2, 1, 9, 3])

In [68]:
x.ravel(order='c')

array([5, 4, 2, 1, 9, 3])

In [69]:
x.ravel(order='f')

array([5, 1, 4, 9, 2, 3])

In [71]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [72]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
x = np.arange(1,4) # concatenate
y = np.arange(4,7)
print(x)
print(y)

[1 2 3]
[4 5 6]


In [75]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [76]:
x = np.arange(10).reshape(2,5)
y = np.arange(10,20).reshape(2,5)
print(x)
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [77]:
np.concatenate([x,y])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [78]:
np.concatenate([x,y],axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [80]:
x = np.arange(12) #split
np.split(x,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [82]:
x = np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [83]:
np.split(x,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [85]:
x = np.arange(16).reshape(4,4)
np.split(x,2,axis=1)


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [87]:
x = np.arange(1,5).reshape(2,2)
y = np.arange(5,9).reshape(2,2)

print(x)
print()
print(y)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [88]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [89]:
np.transpose(x)

array([[1, 3],
       [2, 4]])

In [90]:
np.linalg.inv(x)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [91]:
np.linalg.det(x)

-2.0000000000000004

In [92]:
np.mean(x)

2.5

In [93]:
np.median(x)

2.5

In [94]:
np.std(x)

1.118033988749895

In [95]:
np.var(x)

1.25

In [96]:
np.sum(x)

10

In [97]:
np.sum(x,axis=1)

array([3, 7])

In [98]:
np.sum(x,axis=0)

array([4, 6])

In [99]:
np.cumsum(x)

array([ 1,  3,  6, 10], dtype=int32)

In [100]:
np.cumprod(x)

array([ 1,  2,  6, 24], dtype=int32)

In [101]:
np.min(x)

1

In [102]:
np.argmin(x)

0

In [103]:
np.argmax(x)

3

In [104]:
np.any(x>4)

False

In [105]:
np.all(x>4)

False

In [113]:
x = np.arange(1,5).reshape(2,2)
print(x)

[[1 2]
 [3 4]]


In [114]:
np.where(x>1)

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))

In [115]:
np.where(x>1,x,-100)

array([[-100,    2],
       [   3,    4]])

In [124]:
x=[1,2,3,4,5,6,7,8,9]
y=[10,20,30,40,50,60,70,80,90]

x = np.array(x).reshape(3,3)
y = np.array(y).reshape(3,3)

print(x+y)
print(x.dot(y))

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [127]:
x = np.linspace(1,20,30)
print(x+10)

[11.         11.65517241 12.31034483 12.96551724 13.62068966 14.27586207
 14.93103448 15.5862069  16.24137931 16.89655172 17.55172414 18.20689655
 18.86206897 19.51724138 20.17241379 20.82758621 21.48275862 22.13793103
 22.79310345 23.44827586 24.10344828 24.75862069 25.4137931  26.06896552
 26.72413793 27.37931034 28.03448276 28.68965517 29.34482759 30.        ]


In [142]:
x = np.random.randint(1,100,size=(2,10,10)) #1,5~9,5~9 
np.where(x[1,5:10,5:10]>=50,1,2)

array([[2, 1, 1, 2, 2],
       [2, 1, 2, 2, 1],
       [2, 1, 1, 2, 2],
       [1, 2, 1, 1, 1],
       [1, 2, 1, 1, 2]])

In [143]:
import pandas as pd

In [148]:
x = [1,2,3,4,5]
s = pd.Series(x)
print(s)
print(s.index)
print(s.values)

0    1
1    2
2    3
3    4
4    5
dtype: int64
RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]


In [149]:
x = [1,2,3,4,5]
s = pd.Series(x, index=['a','b','c','d','e'])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [150]:
s['a']

1

In [151]:
s[['a','d']]

a    1
d    4
dtype: int64

In [153]:
x = {"수학":90, "영어":80, "과학":95, "미술":80}
x = pd.Series(x)
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [155]:
x.index

Index(['수학', '영어', '과학', '미술'], dtype='object')

In [154]:
x['수학']

90

In [156]:
x['영어':'미술']

영어    80
과학    95
미술    80
dtype: int64

In [158]:
x[['영어','과학']]

영어    80
과학    95
dtype: int64

In [159]:
x = {"수학":90, "영어":80, "과학":95, "미술":80}
part = pd.Series(x, index=["수학","영어","과학"])

In [160]:
part

수학    90
영어    80
과학    95
dtype: int64

In [162]:
student_1={"수학":90,"영어":80,"과학":95,"미술":80}
student_2={"수학":70,"영어":90,"과학":100,"미술":70}

#index_1=['홍길동','홍길동','홍길동','홍길동','이몽룡','이몽룡','이몽룡','이몽룡']
#index_2=['수학','영어','과학','미술','수학','영어','과학','미술']

index_1 = ['홍길동' for i in range(len(student_1))] + ['이몽룡' for i in range(len(student_2))]
index_2 = list(student_1.keys()) + list(student_2.keys())

value_all = list(student_1.values())+list(student_2.values())

students = pd.Series(value_all,index=[index_1,index_2])
students


홍길동  수학     90
     영어     80
     과학     95
     미술     80
이몽룡  수학     70
     영어     90
     과학    100
     미술     70
dtype: int64

In [166]:
students['홍길동']['수학']

90

In [168]:
student_1={"수학":90,"영어":80,"과학":95,"미술":80}
student_2={"수학":70,"영어":90,"과학":100,"미술":70}

#index_1=['홍길동','홍길동','홍길동','홍길동','이몽룡','이몽룡','이몽룡','이몽룡']
#index_2=['수학','영어','과학','미술','수학','영어','과학','미술']

index_1 = ['홍길동' for i in range(len(student_1))] + ['이몽룡' for i in range(len(student_2))]
index_2 = [i for i in student_1] + [i for i in student_2]

value_all = list(student_1.values())+list(student_2.values())

students = pd.Series(value_all,index=[index_1,index_2])
students

홍길동  수학     90
     영어     80
     과학     95
     미술     80
이몽룡  수학     70
     영어     90
     과학    100
     미술     70
dtype: int64